const fs = require('fs');
const files = JSON.parse(fs.readFileSync('vi_lines.json'));

const dict = {
    // src/app/(reader)/_components
    '{/* Chế độ đọc */}': '{/* Reading mode */}',
    '{/* Khoảng cách ảnh (chỉ hiện khi long-strip) */}': '{/* Image spacing (only shows in long-strip) */}',
    '{/* Spread offset (chỉ hiện khi double) */}': '{/* Spread offset (only shows in double) */}',
    '/** Pre-computed bởi Reader/index - dùng trực tiếp, bỏ qua tính toán nội bộ */': '/** Pre-computed by Reader/index - used directly, skips internal calculation */',
    '// Sử dụng prop nếu có, ngược lại tính toán từ aggregate (backward-compat)': '// Use prop if available, otherwise calculate from aggregate (backward-compat)',
    '/** Indices của spread hiện tại - [left] hoặc [left, right] */': '/** Indices of current spread - [left] or [left, right] */',
    '/** RTL: đảo thứ tự hiển thị */': '/** RTL: reverse display order */',
    '// RTL đảo thứ tự: trang phải hiển thị trước (trang trái = số nhỏ hơn)': '// RTL reverse order: right page shows first (left page = smaller number)',
    '/** Chia pages thành các spreads cho chế độ 2 trang */': '/** Split pages into spreads for 2-page mode */',
    '// Long-strip: mũi tên = chuyển chương | page modes: mũi tên = chuyển trang': '// Long-strip: arrow = change chapter | page modes: arrow = change page',
    '/** Báo về Reader index mỗi khi trang hiển thị thay đổi (dùng để ưu tiên load) */': '/** Notify Reader index whenever visible page changes (used for prioritized loading) */',
    '// IntersectionObserver - track trang hiện đang hiển thị nhiều nhất': '// IntersectionObserver - track page currently most visible',
    '/** Trạng thái tải của trang này từ useReaderImages */': '/** Load status of this page from useReaderImages */',
    '/** Dùng trong chế độ 2 trang - căn ảnh vào giữa spread */': '/** Used in 2-page mode - center image in spread */',
    '{/* Ảnh chính - chỉ hiển thị khi blob đã sẵn sàng */}': '{/* Main image - only shows when blob is ready */}',
    '/** RTL: click trái = next, click phải = prev */': '/** RTL: click left = next, click right = prev */',
    '// RTL đảo chiều: trái = tiến, phải = lùi': '// RTL reverse direction: left = next, right = prev',

    // pages
    'Tìm kiếm nâng cao - WeebDex': 'Advanced Search - WeebDex',
    'Công cụ tìm kiếm nâng cao WeebDex': 'WeebDex advanced search tool',
    '{/* Có bản dịch + ngôn ngữ bản dịch */}': '{/* Has translation + translation language */}',
    ': `Tác giả ${author.name} trên WeebDex`,': ': `Author ${author.name} on WeebDex`,',
    'const description = manga.description || `Đọc truyện ${title}`;': 'const description = manga.description || `Read manga ${title}`;',
    'Truyện này chưa có chương hoặc không có chương khớp với ngôn ngữ bạn': 'This manga has no chapters or no chapters match your selected',
    'chọn': 'language',
    '//     \"none\", // đếch nhớ sao lại code như này 😳': '//     \"none\", // dont remember why I coded like this 😳',
    '//   toast.error(\"Có lỗi xảy ra, vui lòng thử lại sau!\");': '//   toast.error(\"An error occurred, please try again later!\");',
    'toast.info(\"Bạn cần đăng nhập để sử dụng chức năng này!\");': 'toast.info(\"You need to log in to use this feature!\");',
    '//   toast.success(\"Đã bật thông báo!\");': '//   toast.success(\"Notifications enabled!\");',
    '//   toast.info(\"Đã tắt thông báo!\");': '//   toast.info(\"Notifications disabled!\");',
    ': `Nhóm dịch ${group.name} trên WeebDex`,': ': `Scanlation group ${group.name} on WeebDex`,',
    'Danh sách nhóm dịch trên WeebDex': 'List of scanlation groups on WeebDex',
    'Xóa lịch sử': 'Clear history',
    '// keywords: [\"Lịch sử\", \"History\", \"SuicaoDex\"],': '// keywords: [\"History\", \"SuicaoDex\"],',
    'Thử qua mấy mục khác xem sao 🤪': 'Try other sections 🤪',
    'Xóa khỏi thư viện': 'Remove from library',

    // hook/lib
    '// đặt callbacks logic ở đây để cả Middleware và App đều dùng được logic này': '// put callback logic here so both Middleware and App can use it',
    '//   // bro sửa thành các trang cần protect nhiều thì chuyển nó thành arr rồi map': '// map the pages that need protection',
    '//     // login rồi thì pass còn chưa thì sang login page': '// if logged in, pass, otherwise go to login page',
    '//       // login rồi mà cố vào thì cho về home page': '// if logged in and try to access, redirect to home page',
    '//   toast.error(\"Lỗi\");': '//   toast.error(\"Error\");',
    '{/* <span className=\"truncate text-xs\">mẹ mày béo</span> */}': '{/* */}',
    'throw Object.assign(new Error(error.error || \"Có lỗi xảy ra\"), { status: res.status });': 'throw Object.assign(new Error(error.error || \"An error occurred\"), { status: res.status });',
    'refetchInterval: false, // Không auto revalidate': 'refetchInterval: false, // Do not auto revalidate',
    '// bỏ id cũ nhất': '// remove oldest id',
    '// Giới hạn kích thước của mảng khi lấy từ storage': '// Limit array size when getting from storage',
    '// Giới hạn kích thước của mảng trước khi lưu vào storage': '// Limit array size before saving to storage',
    '// Thêm ID vào danh sách thông báo': '// Add ID to notification list',
    '// Không thêm manga ID vào unread list nữa': '// Do not add manga ID to unread list anymore',
    '// Xóa ID khỏi danh sách thông báo': '// Remove ID from notification list',
    '// Giữ nguyên unread list vì ID trong unread list là chapter ID, không phải manga ID': '// Keep unread list because ID in unread list is chapter ID, not manga ID',
    '// Đánh dấu ID là đã xem': '// Mark ID as seen',
    '// Đánh dấu ID là đã đọc (bỏ khỏi unread)': '// Mark ID as read (remove from unread)',
    '// Đánh dấu ID là chưa đọc (thêm vào unread)': '// Mark ID as unread (add to unread)',
    '// Kiểm tra ID đã được xem chưa': '// Check if ID has been seen',
    '// Kiểm tra ID có trong danh sách thông báo không': '// Check if ID is in notification list',
    '// Kiểm tra ID có chưa đọc không': '// Check if ID is unread',
    '// Xóa tất cả thông báo': '// Clear all notifications',
    '// Xóa tất cả trạng thái đã xem': '// Clear all seen statuses',
    '// Đánh dấu tất cả thông báo là đã đọc': '// Mark all notifications as read',
    '// Kiểm tra nếu đang chạy trên client': '// Check if running on client',
    '// Giá trị mặc định khi SSR': '// Default value on SSR',
    '// đọc state mới nhất mà không cần reset Observer': '// read latest state without resetting Observer',
    '// Map lưu vết các element đang được observe': '// Map tracking observed elements',
    '// Sync State -> Ref (Luôn giữ ref mới nhất)': '// Sync State -> Ref (Always keep ref latest)',
    '// chỉ check Ref': '// only check Ref',
    '// Re-observe tất cả các node đang sống': '// Re-observe all living nodes',
    '// tìm index lớn nhất đang hiển thị': '// find largest visible index',
    '// cleanup cái cũ': '// cleanup old',
    '// React gọi với null thì lấy elements cũ ra xoá': '// React called with null, so clear old elements',
    '* `useReaderImages` - tải ảnh reader qua XHR và quản lý blob URLs.': '* `useReaderImages` - loads reader images via XHR and manages blob URLs.',
    '* - Tối đa MAX_PARALLEL XHR đồng thời': '* - Max MAX_PARALLEL concurrent XHRs',
    '* - Hàng đợi ưu tiên: trang hiện tại trước, rồi lan dần ra hai phía': '* - Priority queue: current page first, then expand outward',
    '* - Retry tự động tối đa MAX_ATTEMPTS lần, delay 3 s mỗi lần': '* - Auto retry max MAX_ATTEMPTS times, 3s delay each',
    '* - Trả về blob URL; giải phóng URL khi unmount': '* - Returns blob URL; releases URL when unmounted',
    'blob: string | null;    // blob URL khi đã tải xong': 'blob: string | null;    // blob URL when loaded',
    '// Ref mirror của state - không cần re-render để đọc': '// Ref mirror of state - no need to re-render to read',
    '// Xây hàng đợi ưu tiên quanh currentIndex': '// Build priority queue around currentIndex',
    '// ── Rebuild queue khi currentIndex thay đổi ──────────────────────────────': '// ── Rebuild queue when currentIndex changes ──────────────────────────────',
    '// Thêm vào đầu queue các trang chưa load quanh currentIndex': '// Add surrounding unloaded pages to head of queue',
    '// Giữ lại những trang đang trong queue cũ nhưng không trùng': '// Keep non-duplicate pages from old queue',
    '// ── Retry thủ công ───────────────────────────────────────────────────────': '// ── Manual retry ───────────────────────────────────────────────────────',
    '// Kiểm tra xác thực': '// Check authentication',
    '// Truy vấn nhanh với select chỉ lấy dữ liệu cần thiết': '// Fast query with select fetching only required data',
    'library: { userId }, // Kết nối thông qua thư viện của người dùng': 'library: { userId }, // Connect via user library',
    '// Tìm hoặc tạo thư viện người dùng bằng upsert để giảm truy vấn': '// Find or create user library with upsert to reduce queries',
    'update: {}, // Không cần cập nhật gì nếu đã tồn tại': 'update: {}, // No need to update if already exists',
    'create: { userId }, // Tạo mới nếu chưa tồn tại': 'create: { userId }, // Create new if not exists',
    '// Xóa Manga khỏi thư viện nếu category là \"NONE\"': '// Delete Manga from library if category is \"NONE\"',
    '// Tìm hoặc tạo Manga': '// Find or create Manga',
    'update: { latestChapterId }, // Cập nhật nếu đã tồn tại': 'update: { latestChapterId }, // Update if already exists',
    'create: { mangadexId: mangaId, latestChapterId }, // Tạo mới nếu chưa tồn tại': 'create: { mangadexId: mangaId, latestChapterId }, // Create new if not exists',
    '// Thêm hoặc cập nhật Manga trong thư viện': '// Add or update Manga in library',
    '// Cập nhật category nếu đã tồn tại': '// Update category if already exists',
    '// Tìm ID thư viện của người dùng': '// Find user library ID',
    '// Lấy tất cả Manga trong thư viện và phân loại': '// Get all library Manga and categorize',
    '// Sử dụng reduce để phân loại Manga': '// Use reduce to categorize Manga',
    '// Tạo mới nếu chưa tồn tại': '// Create new if not exists',
    '// login rồi và vẫn vào auth route thì redirect home page': '// logged in but going to auth route, redirect to home page',
    '// chưa login mà vào protected route thì bắt login': '// not logged in but going to protected route, force login',
    '// để thằng bé đó yên': '// leave him alone',
    '// Không cache API calls từ weebdex (phải luôn fetch mới)': '// Do not cache weebdex API calls (always fetch fresh)',
    '// Không cache các internal API routes (comments, auth, v.v.)': '// Do not cache internal API routes (comments, auth, etc.)',
    '// Cache ảnh cover từ weebdex proxy (CacheFirst, 7 ngày, tối đa 1000 ảnh)': '// Cache cover images from weebdex proxy (CacheFirst, 7 days, max 1000 items)',
    '// Force CORS mode để tránh opaque response (status 0) từ no-cors requests': '// Force CORS mode to avoid opaque response (status 0) from no-cors requests',
    '// Không cache ảnh lỗi (< 1KB) hoặc status !== 200': '// Do not cache error images (< 1KB) or status !== 200',

    // notifications
    '"Vì nhiều lý do, từ giờ SuicaoDex sẽ sử dụng [WeebDex API](https://api.weebdex.org/docs).\\n\\nDù sao thì, xin được gửi lời cảm ơn cuối cùng đến đội ngũ MangaDex. Ai cũng liêm cho đến khi liêms 🥀",': '"For various reasons, MangaHat will now use [WeebDex API](https://api.weebdex.org/docs).\\n\\nAnyway, a final thank you to the MangaDex team. Everyone is honest until they aren\'t 🥀",',
    'trigger: "01/03/2026 - Tài khoản và dữ liệu người dùng",': 'trigger: "01/03/2026 - User account and data",',
    '"Về lý thuyết, tài khoản và dữ liệu người dùng của SuicaoDex là riêng biệt với MangaDex, vì vậy việc đổi API kể trên đúng ra phải ~~không ảnh hưởng gì~~.\\n\\nNhưng vì tôi code đần nên dữ liệu về truyện đã lưu của bạn sẽ tạm không thể sử dụng được, cụ thể vui lòng xem bên dưới.",': '"Theoretically, MangaHat user accounts and data are separate from MangaDex, so switching APIs shouldn\'t have affected anything.\\n\\nHowever, due to my bad coding, your saved manga data is temporarily disabled, details below.",',
    'trigger: "01/03/2026 - Vậy có những gì bị ảnh hưởng?",': 'trigger: "01/03/2026 - So what was affected?",',
    '"I will try to fix the issues below in the future, but no timeline yet 🐧 \\n\\n| Feature | Status | Details |\\n|---|---|---|\\n| Link | ❌ Unavailable | Links using MangaDex uuid (vd: `https://suicaodex.com/manga/56958579-6d1b-4db0-be4f-dd17b828fcf`) will not be accessible. |\\n| Library & Reading History | ⚠️ Limited | Manga saved to account/device and reading history before **02/03/2026** will not be displayed; the Save manga to account feature is temporarily disabled. |\\n| New chapter notifications | 🔕 Temporarily disabled | Was already unstable, temporarily disabled to find a better solution. |\\n| Recommendations & Rankings | 📴 Temporarily hidden | WeebDex only recently started operating, not enough data to calculate. |\\n| Comments | ⚠️ Limited | Comments trước **02/03/2026** will still appear in the `Comments gần đây`, but will not appear in manga using the new API. Comments mới từ sau **02/03/2026** work normally. |",': '"I will try to fix the issues below in the future, but no timeline yet 🐧 \\n\\n| Feature | Status | Details |\\n|---|---|---|\\n| Link | ❌ Unavailable | Links using MangaDex uuid will not be accessible. |\\n| Library & Reading History | ⚠️ Limited | Manga saved to account/device and reading history before **02/03/2026** will not be displayed; the Save manga to account feature is temporarily disabled. |\\n| New chapter notifications | 🔕 Temporarily disabled | Temporarily disabled to find a better solution. |\\n| Recommendations & Rankings | 📴 Temporarily hidden | WeebDex only recently started operating, not enough data to calculate. |\\n| Comments | ⚠️ Limited | Comments before **02/03/2026** will appear in `Recent Comments`, but not on manga using the new API. New comments after **02/03/2026** work normally. |",',
    'label: "Truyện",': 'label: "Manga",',
    'label: "Hệ thống",': 'label: "System",',

    // more UI
    'Temporarily disabled cái này để bảo trì, chịu khó đợi nhé 🤪': 'Temporarily disabled for maintenance, bear with it 🤪',
    'Có thể bạn cần biết': 'Good to know',
    'Tác giả': 'Author',
    'Tác phẩm': 'Works',
    'Đã khoá': 'Locked',
    'Không hoạt động': 'Inactive',
    'Nhóm này chưa đăng tải truyện nào': "This group hasn't uploaded any manga yet",
    'Từ giờ SuicaoDex sẽ sử dụng': 'From now on MangaHat will use',
};

Object.keys(files).forEach(file => {
    let content = fs.readFileSync(file, 'utf8');
    Object.keys(dict).forEach(key => {
        content = content.replace(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), dict[key]);
    });
    fs.writeFileSync(file, content, 'utf8');
});
console.log('Second pass done!');
