const fs = require('fs');
const path = require('path');
const files = JSON.parse(fs.readFileSync('vi_lines.json'));

const dict = {
    'Truyện': 'Manga',
    'Xóa tất cả': 'Clear all',
    'Đăng nhập': 'Login',
    'Thư viện': 'Library',
    'Từ thiết bị': 'From device',
    'Từ tài khoản': 'From account',
    'Tất cả': 'All',
    'Hủy': 'Cancel',
    'Lưu': 'Save',
    'Sửa': 'Edit',
    'Trả lời': 'Reply',
    'Gửi': 'Send',
    'tại đây': 'here',
    'Login bằng:': 'Login using:',
    'Mới cập nhật': 'Latest Updates',
    'mới cập nhật': 'latest updates',
    'Mới Cập Nhật': 'Latest Updates',
    'Đang tìm...': 'Searching...',
    'Gì cũng được': 'Anything',
    'Tìm kiếm nâng cao': 'Advanced Search',
    'Nhóm dịch': 'Scanlation groups',
    'Nội dung': 'Content',
    'Định dạng': 'Format',
    'Thể loại': 'Genre',
    'Chủ đề': 'Theme',
    'Tác giả': 'Author',
    'Trang chủ': 'Home',
    'Website đọc truyện chính thức': 'Official manga reading website',
    'Mồn lèo': 'Cats',
    'Mèo': 'Cats',
    'Ảnh bìa': 'Cover image',
    'tập': 'volume',
    'Đọc truyện': 'Read manga',
    'Về lý thuyết, tài khoản và dữ liệu người dùng của SuicaoDex': 'Theoretically, MangaHat user accounts and data',
    'Vậy có những gì bị ảnh hưởng?': 'So what is affected?',
    'Feature tạm thời không khả dụng': 'Feature temporarily unavailable',
    'có chương mới': 'has a new chapter',
    'Tài khoản và dữ liệu người dùng': 'User account and data',
    'Từ giờ SuicaoDex sẽ sử dụng': 'From now on MangaHat will use',
    'Bạn cần đăng nhập để sử dụng chức năng này!': 'You need to log in to use this feature!',
    'Không thể đọc chương này': 'Cannot read this chapter',
    'Không tìm thấy chương nào': 'No chapters found',
    'Truyện này chưa có chương hoặc không có chương khớp với ngôn ngữ bạn': 'This manga has no chapters or no chapters matching your selected',
    'chọn': 'language',
    'Màu sắc': 'Colors',
    'Chế độ': 'Mode',
    'Sáng': 'Light',
    'Tối': 'Dark',
    'Hệ thống': 'System',
    'Chọn màu bạn thích': 'Choose your favorite color',
    'Tuỳ chỉnh giao diện': 'Customize Interface',
    'Đăng xuất': 'Logout',
    'Dữ liệu được lấy từ:': 'Data fetched from:',
    'con mèo.': 'cats.',
    'Hiện có': 'Currently',
    'Xem ảnh mồn lèo giải trí -': 'Watch cat pictures for fun -',
    'Ngó xem có nhầm trang không ba 😹': 'Did you go to the wrong page? 😹',
    'Hết mèo rồi!': 'No more cats!',
    'Thử load lại trang xem sao nhé 😿': 'Try refreshing the page 😿',
    'Mở pack ngay': 'Open pack now',
    '99% người chơi dừng lại trước khi thắng lớn.': '99% of players quit before hitting it big.',
    'Nhà cái đầu hàng Vi En': 'The leading gacha house in VN',
    'MangaDex đang bảo trì, vui lòng quay lại sau!': 'MangaDex is under maintenance, please come back later!',
    'Chưa có tài khoản? Cứ bấm đi là có.': "Don't have an account? Just click to create one.",
    'Thử qua mấy mục khác xem sao 🤪': 'Try checking other sections 🤪',
    'Bạn chưa lưu truyện vào mục này': "You haven't saved any manga to this section",
    'Bạn cần đăng nhập để dùng chức năng này!': 'You need to log in to use this feature!',
    'Tạm tắt cái này để bảo trì, dùng tạm cái bên kia nhé 🤪': 'Temporarily disabled for maintenance, please use the other one 🤪',
    'Chức năng tạm thời không khả dụng': 'Feature temporarily unavailable',
    'sẽ tự động xóa truyện cũ nhất.': 'will automatically delete the oldest ones.',
    'Ngoài ra, mỗi danh mục chỉ lưu tối đa 500 truyện, khi lưu thêm': 'Also, each category only saves up to 500 manga. Adding more',
    'trình duyệt, thư viện này cũng sẽ bị xóa theo.': 'browser data, this library will also be cleared.',
    'đồng bộ với thư viện lưu trên tài khoản. Nếu bạn xóa dữ liệu': 'sync with the library on your account. If you clear your',
    'Đây là thư viện được lưu trên chính thiết bị của bạn, nó không': 'This library is saved locally on your device, it does not',
    'Đọc đi chứ còn đợi gì nữa 🤪': 'Start reading now! 🤪',
    'Bạn chưa đọc truyện nào': "You haven't read any manga yet",
    'liệu trình duyệt, lịch sử cũng sẽ bị xóa theo.': 'browser data, the history will also be cleared.',
    'Lịch sử đọc được lưu trên chính thiết bị của bạn, nên nếu bạn xóa dữ': 'Reading history is saved locally on your device, so if you clear your',
    'Có thể bạn cần biết:': 'Good to know:',
    'Lịch sử đọc': 'Reading History',
    'Lịch sử đọc truyện': 'Reading History',
    'Nhập từ khóa...': 'Enter keyword...',
    'Thử tìm với từ khóa khác nhé': 'Try searching with different keywords',
    'Truyện này chưa có gợi ý tương tự nào cả!': 'This manga has no recommendations yet!',
    'Truyện mà không có ảnh bìa, lạ vậy ta?': 'Manga without a cover, how strange?',
    'Không có kết quả': 'No results',
    'Nhóm này chưa đăng tải truyện nào': "This group hasn't uploaded any manga yet",
    'Nhóm này không tồn tại hoặc đã bị xoá': 'This group does not exist or has been deleted',
    'Không tìm thấy nhóm': 'Group not found',
    'Đã khoá': 'Locked',
    'Không hoạt động': 'Inactive',
    'Truyện đã đăng': 'Uploaded manga',
    'Tác phẩm': 'Works',
    'Liên hệ': 'Contact',
    'Mô tả': 'Description',
    'Tác giả này không tồn tại hoặc đã bị xoá': 'This author does not exist or has been deleted',
    'Không tìm thấy tác giả': 'Author not found',
    'Tìm tác giả...': 'Search author...',
    'Tác giả này chưa có truyện nào': 'This author has no manga yet',
    'Không có truyện nào': 'No manga found',
    'Có lỗi xảy ra, thử F5 xem sao nhé': 'An error occurred, try refreshing the page',
    'Lỗi mất rồi!': 'An error occurred!',
    'Lỗi mất rồi 😭': 'An error occurred 😭',
    'Lỗi mất rồi 🤪': 'An error occurred 🤪',
    'Try changing filters or keywords nhé': 'Try changing filters or keywords',
    'Không tìm thấy kết quả': 'No results found',
    'Ảnh truyện': 'Manga Image',
    'Khoảng cách ảnh': 'Image Spacing',
    'Chế độ đọc': 'Reading Mode',
    'Không tìm thấy thể loại.': 'Genre not found.',
    'Tìm thể loại...': 'Search genre...',
    '(Chọn tất cả)': '(Select all)',
    'Thử thay đổi bộ lọc hoặc từ khóa': 'Try changing filters or keywords',
    'Thay đổi bộ lọc': 'Change filters'
};

Object.keys(files).forEach(file => {
    let content = fs.readFileSync(file, 'utf8');
    Object.keys(dict).forEach(key => {
        content = content.replace(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), dict[key]);
    });
    fs.writeFileSync(file, content, 'utf8');
});
console.log('Replacements done!');
